/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pp.inicio.departamentos;

/**
 *
 * @author User
 */
public class Financeiro extends javax.swing.JFrame {

    /**
     * Creates new form Fiscal
     */
    public Financeiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpControleFiscal = new javax.swing.JPanel();
        lbTitControleFiscal = new javax.swing.JLabel();
        lbTitNome = new javax.swing.JLabel();
        lbTitNumero = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        lbTitID = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JLabel();
        txt_nome = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        jtbGuiasFiscal = new javax.swing.JTabbedPane();
        jpSitFiscal = new javax.swing.JPanel();
        lbTitFaseFiscal = new javax.swing.JLabel();
        lbTitStatusFiscal = new javax.swing.JLabel();
        lbTitDristribuirFuncResp = new javax.swing.JLabel();
        lbtxtValidaPerfFiscal = new javax.swing.JLabel();
        AdamentoFiscal = new javax.swing.JLabel();
        lbDristribuirFuncResp = new javax.swing.JLabel();
        lbValidaPerfFiscal = new javax.swing.JLabel();
        lbTitDristribuirFuncResp1 = new javax.swing.JLabel();
        lbDristribuirFuncResp1 = new javax.swing.JLabel();
        jpValPerfFiscal = new javax.swing.JPanel();
        btnLimpar1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        btnFechar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        btnIncluir1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnAlterar1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnExcluir1 = new javax.swing.JButton();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        btnPesquisar1 = new javax.swing.JButton();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jpDistResp = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jpDistResp1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnIncluir2 = new javax.swing.JButton();
        btnAlterar2 = new javax.swing.JButton();
        btnExcluir2 = new javax.swing.JButton();
        btnPesquisar2 = new javax.swing.JButton();
        btnLimpar2 = new javax.swing.JButton();
        btnFechar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpControleFiscal.setBackground(new java.awt.Color(245, 245, 245));

        lbTitControleFiscal.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        lbTitControleFiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitControleFiscal.setText("Controle Financeiro");
        lbTitControleFiscal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbTitNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitNome.setText("Nome:");

        lbTitNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitNumero.setText("Nº:");

        txt_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitID.setText("ID:");

        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtbGuiasFiscal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpSitFiscal.setBackground(new java.awt.Color(245, 245, 245));

        lbTitFaseFiscal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTitFaseFiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitFaseFiscal.setText("Fase:");

        lbTitStatusFiscal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTitStatusFiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitStatusFiscal.setText("Status:");

        lbTitDristribuirFuncResp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitDristribuirFuncResp.setText("Emissão de Boleto:");

        lbtxtValidaPerfFiscal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbtxtValidaPerfFiscal.setText("Lançamento na Planilha de Cobrança:");

        AdamentoFiscal.setBackground(new java.awt.Color(245, 245, 245));
        AdamentoFiscal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdamentoFiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdamentoFiscal.setToolTipText("");
        AdamentoFiscal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AdamentoFiscal.setOpaque(true);

        lbDristribuirFuncResp.setBackground(new java.awt.Color(245, 245, 245));
        lbDristribuirFuncResp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDristribuirFuncResp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbDristribuirFuncResp.setOpaque(true);

        lbValidaPerfFiscal.setBackground(new java.awt.Color(245, 245, 245));
        lbValidaPerfFiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValidaPerfFiscal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbValidaPerfFiscal.setOpaque(true);

        lbTitDristribuirFuncResp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTitDristribuirFuncResp1.setText("Lançar Controle de O.S no Control:");

        lbDristribuirFuncResp1.setBackground(new java.awt.Color(245, 245, 245));
        lbDristribuirFuncResp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDristribuirFuncResp1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbDristribuirFuncResp1.setOpaque(true);

        javax.swing.GroupLayout jpSitFiscalLayout = new javax.swing.GroupLayout(jpSitFiscal);
        jpSitFiscal.setLayout(jpSitFiscalLayout);
        jpSitFiscalLayout.setHorizontalGroup(
            jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSitFiscalLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSitFiscalLayout.createSequentialGroup()
                        .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtxtValidaPerfFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTitFaseFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitStatusFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpSitFiscalLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDristribuirFuncResp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbValidaPerfFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDristribuirFuncResp1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lbTitDristribuirFuncResp, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitDristribuirFuncResp1)
                    .addGroup(jpSitFiscalLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(AdamentoFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jpSitFiscalLayout.setVerticalGroup(
            jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSitFiscalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitStatusFiscal)
                    .addComponent(lbTitFaseFiscal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbtxtValidaPerfFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpSitFiscalLayout.createSequentialGroup()
                        .addComponent(lbValidaPerfFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(15, 15, 15)
                .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitDristribuirFuncResp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDristribuirFuncResp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpSitFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDristribuirFuncResp1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitDristribuirFuncResp1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(AdamentoFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jtbGuiasFiscal.addTab("Situação", jpSitFiscal);

        jpValPerfFiscal.setBackground(new java.awt.Color(245, 245, 245));

        btnLimpar1.setText("Limpar");
        btnLimpar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpar1MouseClicked(evt);
            }
        });

        btnFechar1.setText("Fechar");
        btnFechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFechar1MouseClicked(evt);
            }
        });
        btnFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "ID", "Nome", "Data Inicial", "Data Final", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Novo Andamento.:");

        btnIncluir1.setText("Incluir");
        btnIncluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncluir1MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Data de Finalização:");

        btnAlterar1.setText("Alterar");
        btnAlterar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterar1MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Observação:");

        btnExcluir1.setText("Excluir");
        btnExcluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluir1MouseClicked(evt);
            }
        });

        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpValPerfFiscalLayout = new javax.swing.GroupLayout(jpValPerfFiscal);
        jpValPerfFiscal.setLayout(jpValPerfFiscalLayout);
        jpValPerfFiscalLayout.setHorizontalGroup(
            jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValPerfFiscalLayout.createSequentialGroup()
                .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpValPerfFiscalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jpValPerfFiscalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9)
                            .addGroup(jpValPerfFiscalLayout.createSequentialGroup()
                                .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextField5))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpValPerfFiscalLayout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(btnIncluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar1)))
                .addContainerGap())
        );

        jpValPerfFiscalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar1, btnExcluir1, btnFechar1, btnIncluir1, btnLimpar1, btnPesquisar1});

        jpValPerfFiscalLayout.setVerticalGroup(
            jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValPerfFiscalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpValPerfFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar1)
                    .addComponent(btnIncluir1)
                    .addComponent(btnPesquisar1)
                    .addComponent(btnExcluir1)
                    .addComponent(btnLimpar1)
                    .addComponent(btnFechar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jpValPerfFiscalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFormattedTextField5, jFormattedTextField6});

        jtbGuiasFiscal.addTab("Lançamento na Planilha", jpValPerfFiscal);

        jpDistResp.setBackground(new java.awt.Color(245, 245, 245));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Novo Andamento.:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Data de Finalização:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Observação:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "ID", "Nome", "Data Inicial", "Data Final", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnIncluir.setText("Incluir");
        btnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncluirMouseClicked(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpDistRespLayout = new javax.swing.GroupLayout(jpDistResp);
        jpDistResp.setLayout(jpDistRespLayout);
        jpDistRespLayout.setHorizontalGroup(
            jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDistRespLayout.createSequentialGroup()
                .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDistRespLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jpDistRespLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8)
                            .addGroup(jpDistRespLayout.createSequentialGroup()
                                .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextField3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDistRespLayout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );

        jpDistRespLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnFechar, btnIncluir, btnLimpar, btnPesquisar});

        jpDistRespLayout.setVerticalGroup(
            jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDistRespLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDistRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnIncluir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnFechar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jpDistRespLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFormattedTextField3, jFormattedTextField4});

        jtbGuiasFiscal.addTab("Emissão de Boleto", jpDistResp);

        jpDistResp1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Novo Andamento.:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Data de Finalização:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Observação:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "ID", "Nome", "Data Inicial", "Data Final", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        btnIncluir2.setText("Incluir");
        btnIncluir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncluir2MouseClicked(evt);
            }
        });

        btnAlterar2.setText("Alterar");
        btnAlterar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterar2MouseClicked(evt);
            }
        });

        btnExcluir2.setText("Excluir");
        btnExcluir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluir2MouseClicked(evt);
            }
        });

        btnPesquisar2.setText("Pesquisar");
        btnPesquisar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisar2MouseClicked(evt);
            }
        });

        btnLimpar2.setText("Limpar");
        btnLimpar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpar2MouseClicked(evt);
            }
        });

        btnFechar2.setText("Fechar");
        btnFechar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFechar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpDistResp1Layout = new javax.swing.GroupLayout(jpDistResp1);
        jpDistResp1.setLayout(jpDistResp1Layout);
        jpDistResp1Layout.setHorizontalGroup(
            jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDistResp1Layout.createSequentialGroup()
                .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDistResp1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jpDistResp1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10)
                            .addGroup(jpDistResp1Layout.createSequentialGroup()
                                .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextField7))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDistResp1Layout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(btnIncluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar2)))
                .addContainerGap())
        );

        jpDistResp1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar2, btnExcluir2, btnFechar2, btnIncluir2, btnLimpar2, btnPesquisar2});

        jpDistResp1Layout.setVerticalGroup(
            jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDistResp1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDistResp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar2)
                    .addComponent(btnIncluir2)
                    .addComponent(btnPesquisar2)
                    .addComponent(btnExcluir2)
                    .addComponent(btnLimpar2)
                    .addComponent(btnFechar2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jpDistResp1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFormattedTextField7, jFormattedTextField8});

        jtbGuiasFiscal.addTab("Lançar Controle de O.S no Control", jpDistResp1);

        javax.swing.GroupLayout jpControleFiscalLayout = new javax.swing.GroupLayout(jpControleFiscal);
        jpControleFiscal.setLayout(jpControleFiscalLayout);
        jpControleFiscalLayout.setHorizontalGroup(
            jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpControleFiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpControleFiscalLayout.createSequentialGroup()
                        .addGroup(jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitNumero)
                            .addComponent(lbTitID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTitControleFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbGuiasFiscal))
                .addContainerGap())
        );
        jpControleFiscalLayout.setVerticalGroup(
            jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpControleFiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitControleFiscal)
                .addGap(18, 18, 18)
                .addGroup(jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTitNome)
                        .addComponent(lbTitNumero)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpControleFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitID)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jtbGuiasFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpControleFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpControleFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirMouseClicked

    }//GEN-LAST:event_btnIncluirMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
     
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
     
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
     
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
     
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnLimpar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar1MouseClicked

    private void btnFechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFechar1MouseClicked

    private void btnIncluir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluir1MouseClicked

    private void btnAlterar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterar1MouseClicked

    private void btnExcluir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluir1MouseClicked

    private void btnPesquisar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisar1MouseClicked

    private void btnFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFechar1ActionPerformed

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked

    }//GEN-LAST:event_btnFecharMouseClicked

    private void btnIncluir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluir2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluir2MouseClicked

    private void btnAlterar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterar2MouseClicked

    private void btnExcluir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluir2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluir2MouseClicked

    private void btnPesquisar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisar2MouseClicked

    private void btnLimpar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar2MouseClicked

    private void btnFechar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFechar2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Financeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdamentoFiscal;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterar1;
    private javax.swing.JButton btnAlterar2;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnExcluir2;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFechar1;
    private javax.swing.JButton btnFechar2;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnIncluir1;
    private javax.swing.JButton btnIncluir2;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel jpControleFiscal;
    private javax.swing.JPanel jpDistResp;
    private javax.swing.JPanel jpDistResp1;
    private javax.swing.JPanel jpSitFiscal;
    private javax.swing.JPanel jpValPerfFiscal;
    private javax.swing.JTabbedPane jtbGuiasFiscal;
    private javax.swing.JLabel lbDristribuirFuncResp;
    private javax.swing.JLabel lbDristribuirFuncResp1;
    private javax.swing.JLabel lbTitControleFiscal;
    private javax.swing.JLabel lbTitDristribuirFuncResp;
    private javax.swing.JLabel lbTitDristribuirFuncResp1;
    private javax.swing.JLabel lbTitFaseFiscal;
    private javax.swing.JLabel lbTitID;
    private javax.swing.JLabel lbTitNome;
    private javax.swing.JLabel lbTitNumero;
    private javax.swing.JLabel lbTitStatusFiscal;
    private javax.swing.JLabel lbValidaPerfFiscal;
    private javax.swing.JLabel lbtxtValidaPerfFiscal;
    public static javax.swing.JLabel txt_codigo;
    public static javax.swing.JLabel txt_id;
    public static javax.swing.JLabel txt_nome;
    public static javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
