/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.prolink.model;

/**
 *
 * @author tiago
 */
public enum ProcessoDocumentoEnum {
    AFASTAMENTO,
    ATOCONSTITUTIVO,
    BALANCETEEXERCICIO,
    BALANCODRE,
    CAGED,
    COMPROVANTERESIDENCIA,
    COMPOSICAODECONTASPATRIMONIAIS,
    RGECPFSOCIO,
    FERIAS,
    LIVROOUFICHADEREGISTROFUNCIONARIO,
    AUTORIZACAONOTAFISCALELETRONICA,
    SENHAINSS,
    NUMEROPIS,
    PLANODECONTAS,
    SENHAPOSTOFISCAL,
    CONFIGURARPERFILFISCALNOSITEPREFEITURADOCUMENTO,
    OUTORGASENHAELETRONICARECEITA,
    RECISAO,
    SENHASIMPLESNACIONAL,
    TERMODERESPONSABILIDADEDOCUMENTO,
    FOLHADEPAGAMENTODOCUMENTO;
}
