/*
 * Todos direitos reservados a Tiago Dias de Souza
 * www.github.com/tiagods
 */
package br.com.prolink.inicio.administracaoAlertas;

import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class AdministradorDePendencias extends javax.swing.JInternalFrame {
    
    InternoComercial intComercial;
    InternoGeral intGeral;
    InternoContratos intContratos;
    InternoContabil intContabil;
    InternoRegularizacao intReg;
    InternoPessoal intPessoal;
    InternoFiscal intFiscal;
    
    /**
     * Creates new form AdministradorDePendencias
     */
    public AdministradorDePendencias() {
        initComponents();
        intGeral = new InternoGeral();
        openInternal(intGeral);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trArvore = new javax.swing.JTree();
        jDkBody = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1148, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Processos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Visão Geral");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Comercial");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Contabil");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Contratos");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Fiscal");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Pessoal");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Regularização");
        treeNode1.add(treeNode2);
        trArvore.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        trArvore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        trArvore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trArvoreMouseClicked(evt);
            }
        });
        trArvore.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                trArvoreValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(trArvore);

        jDkBody.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout jDkBodyLayout = new javax.swing.GroupLayout(jDkBody);
        jDkBody.setLayout(jDkBodyLayout);
        jDkBodyLayout.setHorizontalGroup(
            jDkBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jDkBodyLayout.setVerticalGroup(
            jDkBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDkBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(jDkBody)
        );

        setBounds(0, 0, 1148, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        this.setLocation(0,0);
    }//GEN-LAST:event_formComponentMoved

    private void trArvoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trArvoreMouseClicked
        String menu = trArvore.getLastSelectedPathComponent().toString();
        
        switch(menu){
            case "Comercial":
                intComercial = new InternoComercial();
                openInternal(intComercial);
                break;
            case "Contabil":
                intContabil = new InternoContabil();
                openInternal(intContabil);
                break;
            case "Contratos":
                intContratos = new InternoContratos();
                openInternal(intContratos);
                break;
            case "Fiscal":
                intFiscal = new InternoFiscal();
                openInternal(intFiscal);
                break;
            case "Pessoal":
                intPessoal = new InternoPessoal();
                openInternal(intPessoal);
                break;
            case "Regularização":
                intReg = new InternoRegularizacao();
                openInternal(intReg);
                break;
            default:
                intGeral = new InternoGeral();
                openInternal(intGeral);
                break;
                
        }
    }//GEN-LAST:event_trArvoreMouseClicked

    private void trArvoreValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_trArvoreValueChanged
            
    }//GEN-LAST:event_trArvoreValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDkBody;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree trArvore;
    // End of variables declaration//GEN-END:variables
private void openInternal(JInternalFrame iframe){
    jDkBody.removeAll();
   ((BasicInternalFrameUI)iframe.getUI()).setNorthPane(null);
    jDkBody.add(iframe);
    iframe.setVisible(true);
}
}
