/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.prolink.login;

import br.com.prolink.inicio.Conexao;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Tiago Dias
 */
public class RecuperarAcesso extends javax.swing.JFrame {
    
    Conexao con_recuperar;
    
    String email, usuario, nome, senha;
    
    Properties props = new Properties();
    Session session = Session.getDefaultInstance(props,
                        new javax.mail.Authenticator() {
                             protected PasswordAuthentication getPasswordAuthentication() 
                             {
                                   return new PasswordAuthentication("suporte.ti@prolinkcontabil.com.br", "plkc2004");
                             }
                        });
    public RecuperarAcesso() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtRecuperar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperar Acesso");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Recuperar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtRecuperar.setBackground(new java.awt.Color(254, 254, 254));
        txtRecuperar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRecuperar.setText("@prolinkcontabil.com.br");
        txtRecuperar.setToolTipText("");
        txtRecuperar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRecuperarKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Informe o seu e-mail corporativo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRecuperarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecuperarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            enviar();
        }
    }//GEN-LAST:event_txtRecuperarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarAcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRecuperar;
    // End of variables declaration//GEN-END:variables
    public void enviar(){
        if(txtRecuperar.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Informe um e-mail válido!");
        }  
        else{
            con_recuperar = new Conexao();
            con_recuperar.conecta();
            try{
                
                
                email=txtRecuperar.getText().trim();
                con_recuperar.executeSQL("select * from login where Email='"+txtRecuperar.getText().trim()+"'");
                if(con_recuperar.resultset.first()){
                    
                    usuario = con_recuperar.resultset.getString("Usuario");
                    senha = con_recuperar.resultset.getString("Senha");
                    nome = con_recuperar.resultset.getString("Nome");
                    
                    /** Parâmetros de conexão com servidor Gmail */
                    props.put("mail.smtp.host", "smtp.prolinkcontabil.com.br");
                    //props.put("mail.smtp.socketFactory.port", "587");
                    //props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
                    props.put("mail.smtp.auth", "true");
                    props.put("mail.smtp.port", "587");
                    /** Ativa Debug para sessão */

                    session.setDebug(true);

                     try {
                          Message message = new MimeMessage(session);
                          message.setFrom(new InternetAddress("suporte.ti@prolinkcontabil.com.br")); //Remetente

                          Address[] toUser = InternetAddress //Destinatário(s)
                                     .parse(email);  

                          message.setRecipients(Message.RecipientType.TO, toUser);
                          //message.setSubject("Enviando email com JavaMail");//Assunto
                          message.setSubject("Recuperação de Acesso Controle de Processos");

                          //message.setText("Enviei este email utilizando JavaMail com minha conta GMail!");
                          message.setText("Olá "+nome+",\n\n Conforme solicitado, \nSegue seu acesso para o sistema interno de Controle de Processos\n\n"+
                                            "Usuario: "+usuario+"\nSenha: "+senha+"\n\nIgnore esse e-mail caso você não tenha solicitado");

                          /**Método para enviar a mensagem criada*/
                          Transport.send(message);

                          JOptionPane.showMessageDialog(null, "Em instantes você receberá um e-mail com os seus dados de acesso!!!");

                          dispose();

                     } catch (MessagingException e) {
                          throw new RuntimeException(e);
                     }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Email informado não existe no cadastro");
                }
            }catch(SQLException erro){
                JOptionPane.showMessageDialog(null, "Verifique sua conexao com a internet!\n" +erro);
            }
            con_recuperar.desconecta();
        }
    }
}
